version: '3.9'

services:
  api:
    image: cloudvision:latest
    ports:
      - 5000:5000
    depends_on:
      - "db"
      - "cache"
  cache:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379
  db:
    image: postgres:17.2-alpine3.21
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgrespwd
      - POSTGRES_DB=cloudvision
    secrets:
      - postgrespwd
secrets:
  postgrespwd:
    file: ./pgpwd.txt
      

  

  